# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.synced_folder "./../../..", "/wolk"
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20191218.0.0"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = "wolk-ubuntu-no-docker"
    vb.memory = "1024"
    vb.gui = true
  end
end
