version: '3.7'
services:
  wolk:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      urls: http://0.0.0.0:5998
      ConnectionStrings:WolkDatabase: Data Source=/var/wolk/wolk.db
      IdentityConfiguration:ExpirationInSeconds: 86400
      WolkConfiguration:UploadsPath: /var/wolk/uploads
      IdentityConfiguration:JwtSecret: 2ed5b050-1a68-4be9-8f9d-2bfcb2f6d168
      WolkConfiguration:DefaultLoginEmail: duco@ducode.org
      WolkConfiguration:DefaultPassword: Password123!
    ports:
      - "5998:5998"
    volumes:
      - /tmp:/tmp
      - /srv/wolk:/var/wolk